name: Continuous Integration

on: [pull_request]

jobs:
  lint:
    name: Lint and Format Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.21'

      - name: Check Formatting with gofmt
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            echo 'Code is not formatted with gofmt, please format your code by running gofmt -w . on your changes.'
            exit 1
          fi

      - name: Install templ
        run: go install github.com/a-h/templ/cmd/templ@latest

      - name: Check templ formatting
        run: |
          templ fmt .
          if ! git diff --exit-code; then
            echo "Code is not formatted according to 'templ fmt', please format your code and resubmit!"
            exit 1
          fi

      - name: Commitlint
        uses: aevea/commitsar@v0.20.2
